[build]
  publish = "web_build"

# Configurações de cabeçalhos HTTP para otimizar performance e segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
    Access-Control-Allow-Origin = "*"

# Evita cache persistente para o arquivo HTML principal e binários do jogo
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.pck"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.wasm"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
